

Vagrant.configure("2") do |config|
  config.vm.box = "@@VM_BOX@@"
  #config.vm.box = "debian/jessie64"
  # config.vm.box_url = "./package.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    # set name of vm in virtualbox
    vb.name = "@@VM_NAME@@"
  end
  config.vm.network "private_network", type: "dhcp",name: "vboxnet1",virtualbox__intnet: false
  #config.vm.network "public_network", ip: "192.168.56.10"
  config.vm.define "init_lab"
  # Remove any other network configurations
  config.vm.provision "shell", path: "script.sh"
  # set name to vm in vagrant 
  config.vm.hostname = "@@VM_NAME@@"
  
end